version: '3.0'
services:
  fuseki:
    command: [ "--tdb2", "--update", "--loc=/fuseki/databases/db", "/ontology" ]
    build:
      context: ./jena/
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jena/logs:/fuseki/logs
      - ./jena/databases:/fuseki/databases
      
  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - fuseki

  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"

